apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nbjnnqzvy-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-java-quarkus:d7ee9269eeca19ed480084e61281d2a8ba4853e9@sha256:d1dd20507fb5acb8382e07d867679ed152366355890fe15d7855d3b95e7ebb1c
          name: container-image
